routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.base');
// });

// Route::get('/categories', function () {
//     return view('front.control');
// })->name('control');
Route::middleware(['auth'])->group(function(){


Route::get('/', [App\Http\Controllers\CompanyController::class, 'first'])->name('index');

//Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'index'])->name('control');


Route::get('/categories', [App\Http\Controllers\CategoryController::class, 'index'])->name('categories.index');
Route::get('/categories/create', [App\Http\Controllers\CategoryController::class, 'create'])->name('categories.create');
Route::post('/categories', [App\Http\Controllers\CategoryController::class, 'store'])->name('categories.store');
Route::get('/categories/{category}/edit', [App\Http\Controllers\CategoryController::class, 'edit'])->name('categories.edit');
Route::patch('/categories/{category}/update', [App\Http\Controllers\CategoryController::class, 'update'])->name('categories.update');
Route::delete('/categories/{category}/destroy', [App\Http\Controllers\CategoryController::class, 'destroy'])->name('categories.destroy');


Route::get('/category/{category}/companies', [App\Http\Controllers\CompanyController::class, 'index'])->name('companies.index');
Route::get('/category/{category}/companies/create', [App\Http\Controllers\CompanyController::class, 'create'])->name('companies.create');
Route::post('/category/{category}/companies', [App\Http\Controllers\CompanyController::class, 'store'])->name('companies.store');
Route::get('/category/companies/edit/{company}', [App\Http\Controllers\CompanyController::class, 'edit'])->name('companies.edit');
Route::delete('/category/companies/destroy/{company}', [App\Http\Controllers\CompanyController::class, 'destroy'])->name('companies.destroy');
Route::patch('/category/companies/update/{company}', [App\Http\Controllers\CompanyController::class, 'update'])->name('companies.update');
Route::get('/category/companies/{company}', [App\Http\Controllers\CompanyController::class, 'show'])->name('companies.show');
Route::get('/category/companies/{company}/download', [App\Http\Controllers\CompanyController::class, 'download'])->name('companies.download');



Route::get('/users', [App\Http\Controllers\UserController::class, 'index'])->name('users.index');
Route::get('/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');
Route::post('/users', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');
Route::get('/users/{user}/edit', [App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');
Route::patch('/users/{user}/update', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
Route::delete('/users/{user}/destroy', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroy');


Route::get('/subcategories', [App\Http\Controllers\CategoryController::class, 'index'])->name('subcategories.index');



// Route::get('/category/create', [App\Http\Controllers\CategoryController::class, 'create'])->name('subcategories.create');
// Route::post('/subcategories', [App\Http\Controllers\CategoryController::class, 'store'])->name('subcategories.store');
// Route::get('/subcategories/{category}/edit', [App\Http\Controllers\CategoryController::class, 'edit'])->name('subcategories.edit');
// Route::patch('/subcategories/{category}/update', [App\Http\Controllers\CategoryController::class, 'update'])->name('subcategories.update');
// Route::delete('/subcategories/{category}/destroy', [App\Http\Controllers\CategoryController::class, 'destroy'])->name('subcategories.destroy');

});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

    protected $guarded=[];

    protected $casts=[
        'email'=>'array',
        'phone'=>'array',
        'link'=>'array'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    // public function subcategory()
    // {
    //     return $this->belongsTo(Subcategory::class);
    // }

    public function getImageAttribute($value) {
        if (strpos($value, 'https://') !== FALSE || strpos($value, 'http://') !== FALSE) {
            return $value;
        }
        if($value===null)
        {
            return null;
        }
        return asset('storage/images/companies/' . $value);
    }


    public function getBruchoureAttribute($value) {
        if (strpos($value, 'https://') !== FALSE || strpos($value, 'http://') !== FALSE) {
            return $value;
        }
        if($value===null)
        {
            return null;
        }
        return asset('storage/images/companies/' . $value);
    }
    
    
    public function getProfileAttribute($value) {
        if (strpos($value, 'https://') !== FALSE || strpos($value, 'http://') !== FALSE) {
            return $value;
        }
        if($value===null)
        {
            return null;
        }
        
        return'storage/profiles/' . $value;
    }
}

resources/views/category-partial.blade.php
<ul class="sub submenu-{{$x}}">
     @foreach ($children as $child)
          @if ($child->children->count()>0)
               <li class="contain-submenu"><a href="#">{{$child->name}}</a>
                    @php
                        if($x==3)
                        {
                             $x=0;
                        }
                    @endphp
                    @include('category-partial ',['children' => $child->children ,'x'=>($x+1)])
               </li>
          @else
               <li class="active"><a href="{{route('companies.index',$child->id)}}">{{$child->name}}</a></li>
          @endif
     @endforeach
</ul>

resources/views/child-category-option.blade.php
@if (! in_array($category->id,App\Models\Company::get('category_id')->toArray()))

     <option value="{{ $category->id }}">
          
          {{-- @while ($category->parent_id !== null)
               {{ $category->name }}/   
          @endwhile --}}
          @php
               $copyCategory=$category;
               $string="";
               while ($copyCategory) {
                    $string = $copyCategory->name ."/". $string;
                    $copyCategory=$copyCategory->parent;
               }

               echo $string;
          @endphp
     
     
     </option>
     @foreach ($category->children as $child)
          @include('child-category-option', [ 'category' => $child])

     @endforeach

@endif

resources/views/child-category-view.blade.php
@if(!empty($category->children))
    <ol class="dd-list list-group">
        @foreach($category->children as $kk => $sub_category)
            <li class="dd-item list-group-item " data-id="{{ $sub_category['id'] }}" >
                <div class="dd-handle" >{{ $sub_category['name'] }}</div>
                <div class="dd-option-handle">
                    <a href="{{ route('categories.edit',  $sub_category['id'] ) }}" class="btn btn-success btn-sm" >تعديل</a> 
                    {{-- <a href="{{ route('categories.destroy',  $sub_category['id'] ) }}" class="btn btn-danger btn-sm" >Delete</a> --}}
                    <div id="id02" class="modal">
                        <span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">×</span>
                        <form class="modal-content" action="/action_page.php">
                        <div class="container">
                              <h4 style=" color: #000000;
                             text-align: center;
                             margin-top: 3px;
                             margin-bottom: 9px;
                             font-size: 45px;
                             font-weight: bold;"
                        > حذف هذا القسم سيؤدي إلى حذف جميع الأقسام بداخله</h4>
                             <p> هل أنت متأكد أنك تريد حذف القسم ؟</p>
                        
                             <div class="clearfix">
                             <button type="button" onclick="document.getElementById('id02').style.display='none'" class="cancelbtn">إلغاء</button>
                             <button type="button" onclick="document.getElementById('id02').style.display='none';event.preventDefault();document.getElementById('delete{{$sub_category->id}}').submit();" class="deletebtn"  ><a href="{{route('categories.destroy',$sub_category['id'])}}"></a> تأكيد </button>
                             </div>
                        </div>
                        </form>
                   </div>
                    <a  class="btn btn-danger btn-sm" onclick="document.getElementById('id02').style.display='block'" style="cursor: pointer;">حذف</a> 
                         <form id="delete{{$sub_category['id']}}"  method="post" action="{{route('categories.destroy',$sub_category->id)}}" enctype="multipart/form-data" style="display:none;">
                              @csrf
                              @method('DELETE')
                              {{-- <button class="btn btn-danger">حذف</button> --}}
                         </form>
               </div>

                @include('child-category-view', [ 'category' => $sub_category])
            </li>
        @endforeach
    </ol>
@endif

resources/views/index.blade.php
@extends('layouts.base')
@section('content')
<div class="container-fluid">
@if (Session::has('company-created-message'))
     <div class="alert alert-info">
          {{Session::get('company-created-message')}}
     </div>
@endif

@if (Session::has('company-updated-message'))
     <div class="alert alert-success">
          {{Session::get('company-updated-message')}}
     </div>
@endif
@if (Session::has('company-deleted-message'))
     <div class="alert alert-danger">
          {{Session::get('company-deleted-message')}}
     </div>
@endif

<div>
     <h3 style="font-size: 35px; margin-top:-6px;margin-bottom:7px; background-color:#e2e2e2; padding-left:5px; border-radius:4px; direction:rtl;">
          الرئيسية
     </h3>
</div>

<div class="form-group has-warning has-feedback input-group col-sm-12" style="width: 100%;
margin-left: 0;
margin-top: 100px;
margin-bottom: 30px;">
<form action="{{route('index')}}" method="get">
     @csrf
     <input type="text" class="form-control" placeholder="ابحث عن قسم" name="search" value=" {{request('search')}}"
     style="
     padding-left: 25px;
     border: 1px solid #8b939a;
     right: -3px;
     border-radius: 0px;
     position: absolute;
     color: #8c8c8c;
     font-size: 22px;
     margin-bottom: 171px;
     margin-top: -50px;
     top: -11px;
     height: 59px;
     white-space: nowrap;">

          <button class="btnsearch" type="submit">
               <i class="glyphicon glyphicon-search"></i>
          </button>

</form>
</div>



     <table id="customers">
               <tr>
                    <th>الشركة</th>
                    {{-- <th>صورة الشركة</th> --}}
                    <th>روابط الشركة</th>
                    <th>الايميلات</th>
                    <th>الهواتف</th>
                    <th>البلد</th>
                    <th>عرض</th>
                    {{-- <th>تعديل</th>

                    <th>حذف</th> --}}
               </tr>
               @foreach ($companies as $company)
                    <tr>
                         <td>{{$company->name}}</td>
                         {{-- <td><img src="{{$company->image}}" alt=""   width="50px" height="50px"></td> --}}

                         {{-- <td><a href="{{$company->link}}">اضغط</a></td> --}}

                         <td>
                              <select class="form-control" name="" id="">
                                   @foreach ( ($company->link) as $item)
                                        @if ($item)
                                             <option value="">{{$item}}</option>
                                        @endif
                                   @endforeach
                              </select>
                         </td>
                         <td>
                              <select class="form-control" name="" id="">
                                   @foreach ( ($company->email) as $item)
                                        @if ($item)
                                             <option value="">{{$item}}</option>
                                        @endif
                                   @endforeach
                              </select>
                         </td>
                         <td>
                              <select class="form-control" name="" id="">
                                   @foreach ( ($company->phone) as $item)
                                        @if ($item)
                                             <option value="">{{$item}}</option>
                                        @endif
                                   @endforeach
                              </select>
                         </td>
                         <td>{{$company->country}} </td>
                         <td class="text-center">
                              <a href="{{route('companies.show',$company->id)}}"><button class="btn btn-success">عرض</button></a>
                         </td>
                         {{-- <td class="text-center">
                              <a href="{{route('companies.edit',$company->id)}}"><button class="btn btn-primary">تعديل</button></a>
                         </td>
                         <td class="text-right">
                              <form method="post" action="{{route('companies.destroy',$company->id)}}" enctype="multipart/form-data">
                                   @csrf
                                   @method('DELETE')
                                   <button class="btn btn-danger">حذف</button>
                              </form>
                         </td> --}}
                    </tr>
               @endforeach
          </table>

</div>

@endsection